name: Create Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build --no-configuration-cache

    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: build/libs/*.jar
        generate_release_notes: true
        draft: false
        prerelease: false
        name: Release ${{ github.ref_name }}
        body: |
          ## Backpack for Dummies ${{ steps.get_version.outputs.VERSION }}

          ### Features
          - Accessories mod integration for dedicated backpack slot
          - Configurable keybinding (default: B) to open backpack
          - Full backwards compatibility with chest armor slot

          ### Installation
          1. Download the `.jar` file below
          2. Install NeoForge 21.1.137+ for Minecraft 1.21.1
          3. Place the jar in your `mods` folder
          4. (Optional) Install [Accessories](https://modrinth.com/mod/accessories) for enhanced features

          ### Changes
          See the [README](https://github.com/${{ github.repository }}/blob/master/README.md#changes-from-original) for full changelog.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
